[database]
host = "db.hswbozuueeswplandkdq.supabase.co"
port = 5432
user = "postgres"
password = "l329712881"
database = "postgres"

#postgresql://postgres:[YOUR-PASSWORD]@db.hswbozuueeswplandkdq.supabase.co:5432/postgres